boot:
  read_only_files: []
  editable_files: []
cli:
  ui_theme: mocha
  syntax_theme: monokai
development:
  enable: false
edit_format:
  enable_shell_commands: false
  mask_message_count: 1
files:
  watch:
    enable: true
  ignore:
  - .byte/cache
  - .ruff_cache
  - .idea
  - .venv
  - .env
  - .git
  - .pytest_cache
  - __pycache__
  - node_modules
  - dist
lint:
    enable: true
    commands:
        - command: 
          - uv
          - run
          - ssort
          languages: ['python']
        - command:
          - uv
          - run
          - ruff
          - format
          - --force-exclude
          - --respect-gitignore
          languages:
          - python
        - command:
          - uv
          - run
          - ruff
          - check
          - --fix
          - --force-exclude
          languages:
          - python
        - command: ['keep-sorted']
          languages: ['*']
llm:
  model: gemini
  gemini:
    enable: false
    model_params: {}
  anthropic:
    enable: false
    model_params: {}
  openai:
    enable: false
    model_params: {}
lsp:
  enable: false
  timeout: 30
  servers: {}
presets:
- id: container
  editable_files:
  - elyx/src/elyx/container/container.py
  - elyx/src/elyx/contracts/container/container.py
  - elyx/src/elyx/contracts/container/container_interface.py
  - elyx/src/elyx/exceptions.py
  - elyx/src/elyx/foundation/application.py
  - elyx/src/elyx/foundation/configuration/application_builder.py
  - elyx/src/test/base_test.py
  - elyx/src/test/container/container_test.py
  conventions:
  - COMMENT_STANDARDS.md
  - PROJECT_ARCHITECTURE.md
  prompt: None
  load_on_boot: false
system:
  paths: {}
web:
  enable: true
  chrome_binary_location: /etc/profiles/per-user/sincore/bin/google-chrome-stable

